//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Wpf.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Wpf.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchorables.
        /// </summary>
        internal static string Anchorables {
            get {
                return ResourceManager.GetString("Anchorables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnchorablesSource must be null.
        /// </summary>
        internal static string AnchorablesSourceMustBeNull {
            get {
                return ResourceManager.GetString("AnchorablesSourceMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnchorablesSource must not be bound to anything.
        /// </summary>
        internal static string AnchorablesSourceMustNotBeBoundToAnything {
            get {
                return ResourceManager.GetString("AnchorablesSourceMustNotBeBoundToAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DockingManager is not defined.
        /// </summary>
        internal static string DockingManagerIsNotDefined {
            get {
                return ResourceManager.GetString("DockingManagerIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsSource must be null.
        /// </summary>
        internal static string DocumentsSourceMustBeNull {
            get {
                return ResourceManager.GetString("DocumentsSourceMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsSource must not be bound to anything.
        /// </summary>
        internal static string DocumentsSourceMustNotBeBoundToAnything {
            get {
                return ResourceManager.GetString("DocumentsSourceMustNotBeBoundToAnything", resourceCulture);
            }
        }
    }
}
